LRBMvc/Controllers/ConsentFeesController.cs
using LRB;
using LRBMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LRBMvc.Controllers
{
    public class ConsentFeesController : Controller
    {
        //
        // GET: /ConsentFees/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Calculate()
        {            
            var dict = new Dictionary<string, string>();
            dict["HighValue"]="High Value";
            dict["MediumValue"]= "Medium Value";
            dict["BaseValue"] = "Base Value";
            
            List<int> years = new List<int>();
            for (int i = 1978; i<= 2013; i++)
            {
                years.Add(i);
            }

            ViewBag.Years = years;
            ViewBag.BandValues = dict;
            return View();
        }

        [HttpPost]
        public ActionResult Calculate(ConsentParams consentParams)
        {
            var dict = new Dictionary<string, string>();
            dict["HighValue"] = "High Value";
            dict["MediumValue"] = "Medium Value";
            dict["BaseValue"] = "Base Value";

            List<int> years = new List<int>();
            for (int i = 1978; i <= 2013; i++)
            {
                years.Add(i);
            }

            ViewBag.Years = years;
            ViewBag.BandValues = dict;
            var base_dir = AppDomain.CurrentDomain.BaseDirectory + @"App_Data\data.csv";
            LandFees.init(base_dir);
            var BaseValue = LandFees.Calculate_Consent_Fees(consentParams.Year, consentParams.LandSize, consentParams.LandValue);
            ViewBag.BaseValue = BaseValue;
            try
            {
                
            }
            catch
            {
                
            }
            return View();
        }
    }
}

LRBMvc/Views/ConsentFees/Calculate.cshtml
@{
    ViewBag.Title = "Calculate";
}
@model LRBMvc.Models.ConsentParams


@if (ViewBag.HighValue != null)
{
    <table class="table table-bordered">

        <caption>
            <div style="border: 1px solid #ebccd1; background-color: #f2dede; height: 40px; margin-top: 20px; line-height: 40px; font-size: 17px">CONSENT FEE ASSESSMENT</div>
        </caption>
        <thead>
            <tr>
                <th><strong>High Value Property</strong></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Consent Fees</td>
                <td>@ViewBag.HighValue["ConsentFee"]</td>
            </tr>
            <tr>
                <td>Capital Gains Tax</td>
                <td>@ViewBag.HighValue["CapitalGainsTax"]</td>
            </tr>
            <tr class="warning">
                <td>Total</td>
                <td>@ViewBag.HighValue["Total"]</td>
            </tr>
        </tbody>
    </table>
}

else if (ViewBag.MediumValue != null)
{
    <table class="table table-bordered">

        <caption>
            <div style="border: 1px solid #ebccd1; background-color: #f2dede; height: 40px; margin-top: 20px; line-height: 40px; font-size: 17px">CONSENT FEE ASSESSMENT</div>
        </caption>
        <thead>
            <tr>
                <th><strong>Medium Value Property</strong></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Consent Fees</td>
                <td>@ViewBag.MediumValue["ConsentFee"]</td>
            </tr>
            <tr>
                <td>Capital Gains Tax</td>
                <td>@ViewBag.MediumValue["CapitalGainsTax"]</td>
            </tr>
            <tr class="warning">
                <td>Total</td>
                <td>@ViewBag.MediumValue["Total"]</td>
            </tr>
        </tbody>
    </table>
}

else if (ViewBag.BaseValue != null)
{
    <table class="table table-bordered">

        <caption>
            <div style="border: 1px solid #ebccd1; background-color: #f2dede; height: 40px; margin-top: 20px; line-height: 40px; font-size: 17px">CONSENT FEE ASSESSMENT</div>
        </caption>
        <thead>
            <tr>
                <th><strong>Base Value Property</strong></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Consent Fees</td>
                <td>@ViewBag.BaseValue["ConsentFee"]</td>
            </tr>
            <tr>
                <td>Capital Gains Tax</td>
                <td>@ViewBag.BaseValue["CapitalGainsTax"]</td>
            </tr>
            <tr class="warning">
                <td>Total</td>
                <td>@ViewBag.BaseValue["Total"]</td>
            </tr>
        </tbody>
    </table>
}
else
{
    using (Html.BeginForm())
    {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
                                             
    <div class="form-group">
        <label for="LandValue">What is the size of the Land in SQ. Meters</label>
        @Html.TextBoxFor(model => model.LandSize, new { @type = "number", @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="LandValue">Please state the estimated value of the property</label>
        @Html.DropDownListFor(model => model.LandValue, new SelectList(ViewBag.BandValues, "key", "value"), new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="LandValue">What Year was the Property Surveyed?</label>
        @Html.DropDownListFor(model => model.Year, new SelectList(ViewBag.Years), new { @class = "form-control" })
    </div>
           
    <input type="submit" class="btn btn-default btn-lg pull-right" value="Calculate Estimate" />
    }
}

LRBMvc/Views/ConsentFees/Index.cshtml
@{
    ViewBag.Title = "Consent Fees";
}

<h2>Calculating Consent Fees</h2>
<p>This portal allows you calculate the Consent Fees. To calculate, you are required to enter the size of Land, the Year it was aquired and information about the Value of the land</p>
<a href="#Calculate" data-toggle="modal" data-target="" class="btn btn-default btn-lg">Apply Now</a>

<!-- Modal -->
<div class="modal fade" id="Calculate" tabindex="-1" role="dialog" aria-labelledby="Calculate" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            @using (Html.BeginForm("Calculate", "ConsentFees", FormMethod.Post))
            {
                @Html.ValidationSummary(true)

                <div class="form-group">
                    <label for="LandValue">What is the size of the Land in SQ. Meters</label>
                    <input class="form-control" id="LandSize" />
                </div>
                <div class="form-group">
                    <label for="LandValue">Email address</label>
                    <select class="form-control" id="LandValue">
                        <option value="BaseValue">Base Value</option>
                        <option value="MediumValue">Medium Value</option>
                        <option value="HighValue">High Value</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="LandValue">Email address</label>
                    <select class="form-control" id="LandValue">
                        @for (int i = 1978; i < 2014; i++)
                        {
                            <option value="@i">@i</option>
                        }
                    </select>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            }
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->